import "./globals.css";
import localFont from "next/font/local";
import { Poppins } from "next/font/google";

const poppins = Poppins({
  variable: "--font-poppins",
  subsets: ["latin"],
  weight: ["600", "400", "700"],
  display: "swap",
});

const minionPro = localFont({
  src: [
    { path: "./fonts/MinionPro-Regular.woff2", weight: "400", style: "normal" },
    { path: "./fonts/MinionPro-Medium.woff2", weight: "500", style: "normal" },
  ],
  variable: "--font-minion-pro",
  display: "swap",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${minionPro.variable} ${poppins.variable} antialiased ${
          process.env.NODE_ENV === "development" ? "debug-screens" : ""
        }`}
      >
        {children}
      </body>
    </html>
  );
}
