import "../globals.css";
import localFont from "next/font/local";
import { Poppins } from "next/font/google";
import { notFound } from "next/navigation";
import { NextIntlClientProvider } from "next-intl";
import Navbar from "../components/ui/Navbar";
import Footer from "../components/ui/Footer";

const quattro = localFont({
  src: [
    {
      path: "../fonts/Quattrocento-Regular.ttf",
      weight: "400",
      style: "normal",
    },
  ],
  variable: "--font-quattro",
  display: "swap",
});

const poppins = Poppins({
  variable: "--font-poppins",
  subsets: ["latin"],
  weight: ["600", "400", "700"],
  display: "swap",
});

const minionPro = localFont({
  src: [
    {
      path: "../fonts/MinionPro-Regular.woff2",
      weight: "400",
      style: "normal",
    },
    { path: "../fonts/MinionPro-Medium.woff2", weight: "500", style: "normal" },
  ],
  variable: "--font-minion-pro",
  display: "swap",
});

const futuraDee = localFont({
  src: [
    {
      path: "../fonts/futurano2dee.ttf",
      style: "normal",
      weight: "400",
    },
  ],
  variable: "--font-futura-dee",
  display: "swap",
});

export const metadata = {
  title: "LUEVE - Custom Wedding & Engagement Rings",
  description: "Generated by create next app",
  icons: {
    icon: [{ url: "/images/logo/logo.png", sizes: "16x16", type: "image/png" }],
  },
};

export default async function RootLayout({ children, params }) {
  const { locale } = await params;
  let messages;

  try {
    messages = (await import(`../../messages/${locale}.json`)).default;
  } catch (error) {
    notFound();
  }
  return (
    <html lang={locale}>
      <body
        suppressHydrationWarning
        className={`${quattro.variable} ${minionPro.variable} ${
          poppins.variable
        } ${futuraDee.variable} antialiased ${
          process.env.NODE_ENV === "development" ? "debug-screens" : ""
        }`}
      >
        <NextIntlClientProvider locale={locale} messages={messages}>
          <Navbar />
          <main className="pt-[96px] md:pt-[120px]">{children}</main>
          <Footer />
        </NextIntlClientProvider>
      </body>
    </html>
  );
}
